import {
  createManifestModuleSource,
  loadManifestForPackage,
  resolveManifestPath,
  type BarritsPackageAutomationOptions,
} from "./shared";

type EsbuildOnResolveArgs = { path: string };
type EsbuildOnLoadArgs = { path: string };

type EsbuildPluginBuild = {
  onResolve: (
    options: { filter: RegExp },
    callback: (args: EsbuildOnResolveArgs) => { path: string; namespace?: string } | null,
  ) => void;
  onLoad: (
    options: { filter: RegExp; namespace?: string },
    callback: (args: EsbuildOnLoadArgs) => Promise<{ contents: string; loader: "js" } | null>,
  ) => void;
};

type EsbuildPlugin = {
  name: string;
  setup: (build: EsbuildPluginBuild) => void;
};

type BarritsEsbuildPluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits:manifest";
const DEFAULT_NAMESPACE = "barrits-manifest";

export const barritsEsbuildPlugin = (options: BarritsEsbuildPluginOptions = {}): EsbuildPlugin => {
  const virtualModuleId = options.virtualModuleId ?? DEFAULT_VIRTUAL_MODULE_ID;
  const manifestPath = resolveManifestPath(options.manifestPath ?? options.package?.manifestPath);
  const packageOptions: BarritsPackageAutomationOptions | undefined = options.package
    ? { ...options.package, manifestPath }
    : manifestPath
      ? { manifestPath }
      : undefined;

  return {
    name: "barrits-esbuild-plugin",
    setup(build) {
      build.onResolve({ filter: new RegExp(`^${virtualModuleId.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`) }, () => {
        return {
          path: virtualModuleId,
          namespace: DEFAULT_NAMESPACE,
        };
      });

      build.onLoad({ filter: /.*/, namespace: DEFAULT_NAMESPACE }, async () => {
        const manifest = await loadManifestForPackage(packageOptions);

        return {
          contents: createManifestModuleSource(manifest, "// Generated by barrits esbuild plugin."),
          loader: "js",
        };
      });
    },
  };
};