import {
  createManifestModuleSource,
  loadManifestForPackage,
  createPluginBaseOptions,
  type BarritsPackageAutomationOptions,
} from "./shared";

type EsbuildPlugin = {
  name: string;
  setup: (build: any) => void;
};

type BarritsEsbuildPluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits:manifest";
const RESOLVED_VIRTUAL_PREFIX = "barrits-manifest";

/**
 * [EN] Implementation of Barrits esbuild plugin.
 * [ES] Implementación de Barrits esbuild plugin.
 */
export const barritsEsbuildPlugin = (options: BarritsEsbuildPluginOptions = {}): EsbuildPlugin => {
  const { virtualModuleId, resolvedVirtualModuleId, packageOptions } = createPluginBaseOptions({
    ...options,
    defaultVirtualModuleId: DEFAULT_VIRTUAL_MODULE_ID,
    resolvedPrefix: RESOLVED_VIRTUAL_PREFIX,
  });

  return {
    name: "barrits-esbuild-plugin",
    setup(build) {
      const filter = new RegExp(`^${virtualModuleId}$`);

      build.onResolve({ filter }, (args: { path: string }) => {
        if (args.path === virtualModuleId) {
          return {
            path: resolvedVirtualModuleId,
            namespace: "barrits-manifest",
          };
        }
        return null;
      });

      build.onLoad({ filter: /.*/, namespace: "barrits-manifest" }, async (args: { path: string }) => {
        if (args.path === resolvedVirtualModuleId) {
          const manifest = await loadManifestForPackage(packageOptions);
          const contents = createManifestModuleSource(manifest, "// Generated by barrits esbuild plugin.");
          return {
            contents,
            loader: "js",
          };
        }
        return null;
      });
    },
  };
};