import {
  createManifestModuleSource,
  loadManifestForPackage,
  createPluginBaseOptions,
  type BarritsPackageAutomationOptions,
} from "./shared";

type RollupPlugin = {
  name: string;
  resolveId?: (id: string) => string | null | Promise<string | null>;
  load?: (id: string) => string | null | Promise<string | null>;
};

type BarritsRollupPluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits:manifest";
const RESOLVED_VIRTUAL_PREFIX = "\0";

/**
 * [EN] Implementation of Barrits rollup plugin.
 * [ES] Implementación de Barrits rollup plugin.
 */
export const barritsRollupPlugin = (options: BarritsRollupPluginOptions = {}): RollupPlugin => {
  const { virtualModuleId, resolvedVirtualModuleId, packageOptions } = createPluginBaseOptions({
    ...options,
    defaultVirtualModuleId: DEFAULT_VIRTUAL_MODULE_ID,
    resolvedPrefix: RESOLVED_VIRTUAL_PREFIX,
  });

  return {
    name: "barrits-rollup-plugin",
    resolveId(id) {
      return id === virtualModuleId ? resolvedVirtualModuleId : null;
    },
    async load(id) {
      if (id !== resolvedVirtualModuleId) {
        return null;
      }

      const manifest = await loadManifestForPackage(packageOptions);
      return createManifestModuleSource(manifest, "// Generated by barrits Rollup plugin.");
    },
  };
};