import {
  createManifestModuleSource,
  loadManifestForPackage,
  resolveManifestPath,
  type BarritsPackageAutomationOptions,
} from "./shared";

type RollupPlugin = {
  name: string;
  resolveId?: (id: string) => string | null | Promise<string | null>;
  load?: (id: string) => string | null | Promise<string | null>;
};

type BarritsRollupPluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits:manifest";

export const barritsRollupPlugin = (options: BarritsRollupPluginOptions = {}): RollupPlugin => {
  const virtualModuleId = options.virtualModuleId ?? DEFAULT_VIRTUAL_MODULE_ID;
  const resolvedVirtualModuleId = `\0${virtualModuleId}`;
  const manifestPath = resolveManifestPath(options.manifestPath ?? options.package?.manifestPath);
  const packageOptions: BarritsPackageAutomationOptions | undefined = options.package
    ? { ...options.package, manifestPath }
    : manifestPath
      ? { manifestPath }
      : undefined;

  return {
    name: "barrits-rollup-plugin",
    resolveId(id) {
      return id === virtualModuleId ? resolvedVirtualModuleId : null;
    },
    async load(id) {
      if (id !== resolvedVirtualModuleId) {
        return null;
      }

      const manifest = await loadManifestForPackage(packageOptions);
      return createManifestModuleSource(manifest, "// Generated by barrits Rollup plugin.");
    },
  };
};