import {
  createManifestModuleSource,
  loadManifestForPackage,
  resolveManifestPath,
  type BarritsPackageAutomationOptions,
} from "./shared";

type VitePlugin = {
  name: string;
  resolveId?: (id: string) => string | null | Promise<string | null>;
  load?: (id: string) => string | null | Promise<string | null>;
  config?: () => { define?: Record<string, string> } | void | Promise<{ define?: Record<string, string> } | void>;
};

type BarritsVitePluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "virtual:barrits/manifest";
const RESOLVED_VIRTUAL_PREFIX = "\0virtual:barrits/manifest";

export const barritsVitePlugin = (options: BarritsVitePluginOptions = {}): VitePlugin => {
  const virtualModuleId = options.virtualModuleId ?? DEFAULT_VIRTUAL_MODULE_ID;
  const resolvedVirtualModuleId = `${RESOLVED_VIRTUAL_PREFIX}:${virtualModuleId}`;
  const manifestPath = resolveManifestPath(options.manifestPath ?? options.package?.manifestPath);
  const packageOptions: BarritsPackageAutomationOptions | undefined = options.package
    ? { ...options.package, manifestPath }
    : manifestPath
      ? { manifestPath }
      : undefined;

  return {
    name: "barrits-vite-plugin",
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }

      return null;
    },
    async load(id) {
      if (id !== resolvedVirtualModuleId) {
        return null;
      }

      const manifest = await loadManifestForPackage(packageOptions);
      return createManifestModuleSource(manifest, "// Generated by barrits Vite plugin.");
    },
    config() {
      if (!manifestPath) {
        return;
      }

      return {
        define: {
          __BARRITS_BUILD_MANIFEST__: JSON.stringify(manifestPath),
        },
      };
    },
  };
};