import {
  createManifestModuleSource,
  loadManifestForPackage,
  createPluginBaseOptions,
  type BarritsPackageAutomationOptions,
} from "./shared";

type VitePlugin = {
  name: string;
  resolveId?: (id: string) => string | null | Promise<string | null>;
  load?: (id: string) => string | null | Promise<string | null>;
  config?: () => { define?: Record<string, string> } | void | Promise<{ define?: Record<string, string> } | void>;
};

type BarritsVitePluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "virtual:barrits/manifest";
const RESOLVED_VIRTUAL_PREFIX = "\0virtual:barrits/manifest";

/**
 * [EN] Implementation of Barrits vite plugin.
 * [ES] Implementación de Barrits vite plugin.
 */
export const barritsVitePlugin = (options: BarritsVitePluginOptions = {}): VitePlugin => {
  const { virtualModuleId, resolvedVirtualModuleId, manifestPath, packageOptions } = createPluginBaseOptions({
    ...options,
    defaultVirtualModuleId: DEFAULT_VIRTUAL_MODULE_ID,
    resolvedPrefix: RESOLVED_VIRTUAL_PREFIX,
  });

  return {
    name: "barrits-vite-plugin",
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }

      return null;
    },
    async load(id) {
      if (id !== resolvedVirtualModuleId) {
        return null;
      }

      const manifest = await loadManifestForPackage(packageOptions);
      return createManifestModuleSource(manifest, "// Generated by barrits Vite plugin.");
    },
    config() {
      if (!manifestPath) {
        return;
      }

      return {
        define: {
          __BARRITS_BUILD_MANIFEST__: JSON.stringify(manifestPath),
        },
      };
    },
  };
};
