import { resolve } from "node:path";

import { ensureManifestModuleFile } from "./materialize";
import {
  loadManifestForPackage,
  resolveManifestPath,
  type BarritsPackageAutomationOptions,
} from "./shared";

type WebpackCompiler = {
  context: string;
  options: {
    resolve?: {
      alias?: Record<string, string>;
    };
  };
  hooks: {
    beforeRun: {
      tapPromise: (name: string, callback: () => Promise<void>) => void;
    };
    watchRun: {
      tapPromise: (name: string, callback: () => Promise<void>) => void;
    };
  };
};

type WebpackPlugin = {
  apply: (compiler: WebpackCompiler) => void;
};

type BarritsWebpackPluginOptions = {
  manifestPath?: string;
  package?: BarritsPackageAutomationOptions;
  virtualModuleId?: string;
  generatedModulePath?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits-manifest";
const DEFAULT_GENERATED_MODULE_PATH = ".barrits/webpack-manifest.generated.mjs";

export class BarritsWebpackPlugin implements WebpackPlugin {
  private readonly packageOptions?: BarritsPackageAutomationOptions;
  private readonly virtualModuleId: string;
  private readonly generatedModulePath: string;

  constructor(options: BarritsWebpackPluginOptions = {}) {
    const manifestPath = resolveManifestPath(options.manifestPath ?? options.package?.manifestPath);
    this.packageOptions = options.package ? { ...options.package, manifestPath } : manifestPath ? { manifestPath } : undefined;
    this.virtualModuleId = options.virtualModuleId ?? DEFAULT_VIRTUAL_MODULE_ID;
    this.generatedModulePath = options.generatedModulePath ?? DEFAULT_GENERATED_MODULE_PATH;
  }

  apply(compiler: WebpackCompiler): void {
    const resolvedGeneratedModulePath = resolve(compiler.context, this.generatedModulePath);
    const ensureGeneratedModule = async (): Promise<void> => {
      const manifest = await loadManifestForPackage(this.packageOptions, compiler.context);
      await ensureManifestModuleFile(
        resolvedGeneratedModulePath,
        manifest,
        "// Generated by barrits Webpack plugin.",
      );
    };

    compiler.options.resolve ??= {};
    compiler.options.resolve.alias = {
      ...(compiler.options.resolve.alias ?? {}),
      [this.virtualModuleId]: resolvedGeneratedModulePath,
    };

    compiler.hooks.beforeRun.tapPromise("barrits-webpack-plugin", ensureGeneratedModule);
    compiler.hooks.watchRun.tapPromise("barrits-webpack-plugin", ensureGeneratedModule);
  }
}

export const barritsWebpackPlugin = (options: BarritsWebpackPluginOptions = {}): BarritsWebpackPlugin => {
  return new BarritsWebpackPlugin(options);
};