import { resolve } from "node:path";

import { ensureManifestModuleFile } from "./materialize";
import { loadManifestForPackage, resolveManifestPath, type BarritsPackageAutomationOptions } from "./shared";

/** [EN] Webpack compiler interface used by BarritsWebpackPlugin. [ES] Interfaz de compilador de Webpack utilizada por BarritsWebpackPlugin. */
export type WebpackCompiler = {
  /** [EN] Context. [ES] Contexto. */
  context: string;
  /** [EN] Options. [ES] Opciones. */
  options: {
    /** [EN] Resolve. [ES] Resolve. */
    resolve?: {
      /** [EN] Alias. [ES] Alias. */
      alias?: Record<string, string>;
    };
  };
  /** [EN] Hooks. [ES] Hooks. */
  hooks: {
    /** [EN] Before run. [ES] Before run. */
    beforeRun: {
      /** [EN] Tap promise. [ES] Tap promise. */
      tapPromise: (name: string, callback: () => Promise<void>) => void;
    };
    /** [EN] Watch run. [ES] Watch run. */
    watchRun: {
      /** [EN] Tap promise. [ES] Tap promise. */
      tapPromise: (name: string, callback: () => Promise<void>) => void;
    };
  };
};

/** [EN] Webpack plugin interface used by BarritsWebpackPlugin. [ES] Interfaz de plugin de Webpack utilizada por BarritsWebpackPlugin. */
export type WebpackPlugin = {
  /** [EN] Apply. [ES] Aplicar. */
  apply: (compiler: WebpackCompiler) => void;
};

/**
 * [EN] Configuration options for the Barrits Webpack plugin.
 * [ES] Opciones de configuración para el plugin de Webpack de Barrits.
 */
export type BarritsWebpackPluginOptions = {
  /** [EN] Manifest path. [ES] Manifiesto ruta. */
  manifestPath?: string;
  /** [EN] Package. [ES] Paquete. */
  package?: BarritsPackageAutomationOptions;
  /** [EN] Virtual module id. [ES] Virtual module id. */
  virtualModuleId?: string;
  /** [EN] Generated module path. [ES] Generated module ruta. */
  generatedModulePath?: string;
};

const DEFAULT_VIRTUAL_MODULE_ID = "barrits-manifest";
const DEFAULT_GENERATED_MODULE_PATH = ".barrits/webpack-manifest.generated.mjs";

/**
 * [EN] Webpack plugin that generates and injects the Barrits build manifest as a virtual module.
 * [ES] Plugin de Webpack que genera e inyecta el manifiesto de compilación de Barrits como un módulo virtual.
 */
export class BarritsWebpackPlugin implements WebpackPlugin {
  /** [EN] Package options. [ES] Paquete opciones. */
  private readonly packageOptions?: BarritsPackageAutomationOptions;
  /** [EN] Virtual module id. [ES] Virtual module id. */
  private readonly virtualModuleId: string;
  /** [EN] Generated module path. [ES] Generated module ruta. */
  private readonly generatedModulePath: string;

  /**
   * [EN] Creates a new BarritsWebpackPlugin instance.
   * [ES] Crea una nueva instancia de BarritsWebpackPlugin.
   */
  constructor(options: BarritsWebpackPluginOptions = {}) {
    const manifestPath = resolveManifestPath(options.manifestPath ?? options.package?.manifestPath);
    this.packageOptions = options.package ? { ...options.package, manifestPath } : manifestPath ? { manifestPath } : undefined;
    this.virtualModuleId = options.virtualModuleId ?? DEFAULT_VIRTUAL_MODULE_ID;
    this.generatedModulePath = options.generatedModulePath ?? DEFAULT_GENERATED_MODULE_PATH;
  }

  /**
   * [EN] Applies the plugin to the Webpack compiler, registering hooks for manifest generation.
   * [ES] Aplica el plugin al compilador de Webpack, registrando hooks para la generación del manifiesto.
   */
  apply(compiler: WebpackCompiler): void {
    const resolvedGeneratedModulePath = resolve(compiler.context, this.generatedModulePath);
    const ensureGeneratedModule = async (): Promise<void> => {
      const manifest = await loadManifestForPackage(this.packageOptions, compiler.context);
      await ensureManifestModuleFile(resolvedGeneratedModulePath, manifest, "// Generated by barrits Webpack plugin.");
    };

    compiler.options.resolve ??= {};
    compiler.options.resolve.alias = {
      ...(compiler.options.resolve.alias ?? {}),
      [this.virtualModuleId]: resolvedGeneratedModulePath,
    };

    compiler.hooks.beforeRun.tapPromise("barrits-webpack-plugin", ensureGeneratedModule);
    compiler.hooks.watchRun.tapPromise("barrits-webpack-plugin", ensureGeneratedModule);
  }
}

/**
 * [EN] Factory function that creates a BarritsWebpackPlugin instance.
 * [ES] Función de fábrica que crea una instancia de BarritsWebpackPlugin.
 */
export const barritsWebpackPlugin = (options: BarritsWebpackPluginOptions = {}): BarritsWebpackPlugin => {
  return new BarritsWebpackPlugin(options);
};
