import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { defineBarritsPackage, toBarritsAutomationOptions } from "../src/barrits/package";
import { barritsEsbuildPlugin } from "../src/barrits/plugins/esbuild";
import { extractManifestFromModuleSource, normalizePathSlashes, writeProjectFile } from "./helpers/fixtures";

test("esbuild plugin accepts package-first automation options", async () => {
  const projectRoot = await mkdtemp(join(tmpdir(), "barrits-esbuild-plugin-"));

  await writeProjectFile(projectRoot, "barrits/logic/index.ts", 'export { duplicar } from "./duplicar";\n');
  await writeProjectFile(projectRoot, "barrits/logic/duplicar.ts", "export const duplicar = (value: number) => value * 2;\n");

  let onResolveHandler:
    | ((args: { path: string }) => { path: string; namespace?: string } | null)
    | undefined;
  let onLoadHandler:
    | ((args: { path: string }) => Promise<{ contents: string; loader: "js" } | null>)
    | undefined;

  const plugin = barritsEsbuildPlugin({
    package: toBarritsAutomationOptions(defineBarritsPackage({ runtime: "node", projectRoot })),
  });

  plugin.setup({
    onResolve: (_options, callback) => {
      onResolveHandler = callback;
    },
    onLoad: (_options, callback) => {
      onLoadHandler = callback;
    },
  });

  assert.ok(onResolveHandler);
  assert.ok(onLoadHandler);

  const resolution = onResolveHandler?.({ path: "barrits:manifest" });
  assert.deepEqual(resolution, { path: "barrits-manifest:barrits:manifest", namespace: "barrits-manifest" });

  const loadedModule = await onLoadHandler?.({ path: resolution?.path ?? "barrits-manifest:barrits:manifest" });
  assert.ok(loadedModule);
  assert.match(loadedModule?.contents ?? "", /Generated by barrits esbuild plugin/);

  const manifest = extractManifestFromModuleSource(loadedModule?.contents ?? "");
  assert.ok(manifest);
  assert.deepEqual(manifest?.domains, ["logic"]);
  assert.deepEqual(manifest?.traitDescriptors, []);
  assert.deepEqual(manifest?.traitDiagnostics, []);
  assert.equal(manifest?.projectRoot, normalizePathSlashes(projectRoot));
});
