import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  filterImportActions,
  createImportsModuleSource,
  createImportBlock,
  applyManagedImports,
  AUTO_IMPORTS_START,
  AUTO_IMPORTS_END,
} from "../src/barrits/sdk/imports";
import type { BarritsIntegrationGraph, BarritsImportAction } from "../src/barrits/sdk/contracts";

const makeAction = (overrides: Partial<BarritsImportAction> = {}): BarritsImportAction => ({
  exportName: "hello",
  domain: "root",
  sourceFile: "index.ts",
  kind: "named-import",
  statement: `import { hello } from "@zuccadev-labs/barrits";`,
  ...overrides,
});

const makeGraph = (actions: BarritsImportAction[]): BarritsIntegrationGraph => ({
  projectRoot: "/project",
  barritsDirectory: "/project/barrits",
  strategy: "current-directory",
  discoveryRoots: ["/project/barrits"],
  filesCount: 0,
  exportsCount: 0,
  publicExportsCount: 0,
  internalExportsCount: 0,
  barrelsCount: 0,
  rootFiles: [],
  domains: [],
  libraryRootFiles: [],
  libraryDomains: [],
  traitDescriptors: [],
  traitDiagnostics: [],
  importActions: actions,
  collisions: [],
});

describe("filterImportActions", () => {
  it("returns all actions with no filters", () => {
    const result = filterImportActions(makeGraph([makeAction()]), {});
    assert.equal(result.importActions.length, 1);
  });

  it("filters by domain", () => {
    const result = filterImportActions(
      makeGraph([makeAction({ domain: "logic" }), makeAction({ domain: "api", exportName: "other" })]),
      { domains: ["logic"] },
    );
    assert.equal(result.importActions.length, 1);
    assert.equal(result.importActions[0].domain, "logic");
  });

  it("filters by export name", () => {
    const result = filterImportActions(
      makeGraph([makeAction({ exportName: "keep" }), makeAction({ exportName: "omit" })]),
      { exports: ["keep"] },
    );
    assert.equal(result.importActions.length, 1);
    assert.equal(result.importActions[0].exportName, "keep");
  });

  it("filters by kind", () => {
    const result = filterImportActions(
      makeGraph([makeAction({ kind: "named-import" }), makeAction({ kind: "namespace-access", exportName: "other" })]),
      { kinds: ["namespace-access"] },
    );
    assert.equal(result.importActions.length, 1);
    assert.equal(result.importActions[0].kind, "namespace-access");
  });

  it("returns empty when no actions match filters", () => {
    const result = filterImportActions(makeGraph([makeAction()]), { domains: ["nonexistent"] });
    assert.equal(result.importActions.length, 0);
  });

  it("preserves other graph properties", () => {
    const graph = makeGraph([makeAction()]);
    const result = filterImportActions(graph, { domains: ["root"] });
    assert.equal(result.projectRoot, "/project");
  });
});

describe("createImportsModuleSource", () => {
  it("generates module source with import actions", () => {
    const source = createImportsModuleSource(makeGraph([
      makeAction({ exportName: "hello", domain: "root", kind: "named-import", statement: `import { hello } from "@zuccadev-labs/barrits";` }),
    ]));
    assert.ok(source.includes("importActions"));
    assert.ok(source.includes("hello"));
    assert.ok(source.includes("namedImports"));
    assert.ok(source.includes("namespaceAccess"));
    assert.ok(source.includes("aliasNamespaceAccess"));
    assert.ok(source.includes("importMap"));
  });

  it("sorts actions by domain then exportName", () => {
    const source = createImportsModuleSource(makeGraph([
      makeAction({ exportName: "zExport", domain: "api", statement: `import { zExport } from "@zuccadev-labs/barrits";` }),
      makeAction({ exportName: "aExport", domain: "logic", statement: `import { aExport } from "@zuccadev-labs/barrits";` }),
    ]));
    const apiIdx = source.indexOf('"api"');
    const logicIdx = source.indexOf('"logic"');
    assert.ok(apiIdx > 0);
    assert.ok(logicIdx > 0);
    assert.ok(apiIdx < logicIdx, `Expected api before logic (alphabetical), got apiIdx=${apiIdx} logicIdx=${logicIdx}`);
  });

  it("groups actions by exportName in importMap", () => {
    const source = createImportsModuleSource(makeGraph([
      makeAction({ exportName: "shared", kind: "named-import" }),
      makeAction({ exportName: "shared", kind: "namespace-access" }),
    ]));
    assert.ok(source.includes('"shared"'));
  });

  it("generates valid JS module structure", () => {
    const source = createImportsModuleSource(makeGraph([]));
    assert.ok(source.startsWith("// Generated by barrits."));
    assert.ok(source.includes("export const importActions"));
    assert.ok(source.includes("export const importMap"));
    assert.ok(source.includes("export const namedImports"));
  });
});

describe("createImportBlock", () => {
  it("creates named-import block with export names", () => {
    const block = createImportBlock(makeGraph([
      makeAction({ exportName: "hello", kind: "named-import", statement: `import { hello } from "@zuccadev-labs/barrits";` }),
      makeAction({ exportName: "world", kind: "named-import", statement: `import { world } from "@zuccadev-labs/barrits";` }),
    ]), "named-import");
    assert.ok(block.includes(AUTO_IMPORTS_START));
    assert.ok(block.includes(AUTO_IMPORTS_END));
    assert.ok(block.includes("hello") && block.includes("world"));
    assert.ok(block.includes('from "@zuccadev-labs/barrits"'));
  });

  it("creates empty block when no named-import actions", () => {
    const block = createImportBlock(makeGraph([]), "named-import");
    assert.ok(block.includes(AUTO_IMPORTS_START));
    assert.ok(block.includes(AUTO_IMPORTS_END));
  });

  it("creates namespace-access block", () => {
    const block = createImportBlock(makeGraph([]), "namespace-access");
    assert.ok(block.includes("barrits"));
    assert.ok(block.includes(AUTO_IMPORTS_START));
  });

  it("creates alias-namespace-access block", () => {
    const block = createImportBlock(makeGraph([]), "alias-namespace-access");
    assert.ok(block.includes("brt"));
    assert.ok(block.includes(AUTO_IMPORTS_START));
  });

  it("deduplicates export names", () => {
    const block = createImportBlock(makeGraph([
      makeAction({ exportName: "hello", kind: "named-import" }),
      makeAction({ exportName: "hello", kind: "named-import" }),
    ]), "named-import");
    const match = block.match(/\bhello\b/g);
    assert.equal(match?.length, 1);
  });
});

describe("applyManagedImports", () => {
  it("replaces existing managed import block", () => {
    const source = `${AUTO_IMPORTS_START}\nimport { old } from "@zuccadev-labs/barrits";\n${AUTO_IMPORTS_END}\n\nconst x = 1;`;
    const result = applyManagedImports(source, makeGraph([
      makeAction({ exportName: "hello", kind: "named-import" }),
    ]), "named-import");
    assert.ok(result.includes("hello"));
    assert.ok(!result.includes("old"));
    assert.ok(result.includes("const x = 1;"));
  });

  it("appends block after existing imports", () => {
    const source = "import fs from 'node:fs';\n\nconst x = 1;";
    const result = applyManagedImports(source, makeGraph([
      makeAction({ exportName: "hello", kind: "named-import" }),
    ]), "named-import");
    assert.ok(result.includes("import fs from 'node:fs'"));
    assert.ok(result.includes(AUTO_IMPORTS_START));
    assert.ok(result.includes("const x = 1;"));
  });

  it("prepends block when no existing imports", () => {
    const source = "const x = 1;";
    const result = applyManagedImports(source, makeGraph([
      makeAction({ exportName: "hello", kind: "named-import" }),
    ]), "named-import");
    assert.ok(result.startsWith(AUTO_IMPORTS_START));
    assert.ok(result.includes("const x = 1;"));
  });

  it("handles namespace-access mode", () => {
    const source = "const x = 1;";
    const result = applyManagedImports(source, makeGraph([]), "namespace-access");
    assert.ok(result.includes("barrits"));
    assert.ok(result.includes(AUTO_IMPORTS_START));
  });
});
