import { describe, it, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const tempDirs = new Set<string>();

after(async () => {
  const dirs = [...tempDirs];
  tempDirs.clear();
  await Promise.allSettled(dirs.map((d) => rm(d, { recursive: true, force: true })));
});

import {
  resolveManifestPath,
  createManifestModuleSource,
  createPluginBaseOptions,
  loadManifest,
  resolvePackageAutomationOptions,
  loadManifestOrCreate,
  loadManifestForPackage,
} from "../src/barrits/plugins/shared";

import type { BarritsBuildManifest } from "../src/barrits/sdk/contracts";

const BANNER = "// auto-generated by Barrits";

const makeManifest = (overrides: Partial<BarritsBuildManifest> = {}): BarritsBuildManifest => ({
  checksum: "sha256-barrits-abc123",
  generatedAt: "2025-01-01T00:00:00.000Z",
  projectRoot: "/project",
  barritsDirectory: "/project/barrits",
  strategy: "current-directory",
  discoveryRoots: [],
  filesCount: 0,
  exportsCount: 0,
  publicExportsCount: 0,
  internalExportsCount: 0,
  barrelsCount: 0,
  domains: ["logic"],
  traitDescriptors: [],
  traitDiagnostics: [],
  importActions: [],
  collisions: [],
  ...overrides,
});

describe("resolveManifestPath", () => {
  it("returns the provided manifestPath", () => {
    assert.equal(resolveManifestPath("/custom/manifest.json"), "/custom/manifest.json");
  });

  it("returns undefined when no path and no env var", () => {
    const prev = process.env.BARRITS_BUILD_MANIFEST;
    try {
      delete process.env.BARRITS_BUILD_MANIFEST;
      assert.equal(resolveManifestPath(), undefined);
    } finally {
      if (prev !== undefined) process.env.BARRITS_BUILD_MANIFEST = prev;
      else delete process.env.BARRITS_BUILD_MANIFEST;
    }
  });

  it("falls back to environment variable", () => {
    const prev = process.env.BARRITS_BUILD_MANIFEST;
    try {
      process.env.BARRITS_BUILD_MANIFEST = "/env/manifest.json";
      assert.equal(resolveManifestPath(), "/env/manifest.json");
    } finally {
      if (prev !== undefined) process.env.BARRITS_BUILD_MANIFEST = prev;
      else delete process.env.BARRITS_BUILD_MANIFEST;
    }
  });

  it("explicit path beats environment variable", () => {
    const prev = process.env.BARRITS_BUILD_MANIFEST;
    try {
      process.env.BARRITS_BUILD_MANIFEST = "/env/manifest.json";
      assert.equal(resolveManifestPath("/explicit/manifest.json"), "/explicit/manifest.json");
    } finally {
      if (prev !== undefined) process.env.BARRITS_BUILD_MANIFEST = prev;
      else delete process.env.BARRITS_BUILD_MANIFEST;
    }
  });
});

describe("createManifestModuleSource", () => {
  it("returns null export when manifest is null", () => {
    const source = createManifestModuleSource(null, BANNER);
    assert.match(source, new RegExp(BANNER));
    assert.match(source, /export const manifest = null/);
    assert.match(source, /export default manifest/);
  });

  it("includes JSON-stringified manifest when provided", () => {
    const manifest = makeManifest();
    const source = createManifestModuleSource(manifest, BANNER);
    assert.match(source, new RegExp(BANNER));
    assert.match(source, /export const manifest =/);
    assert.match(source, /"checksum": "sha256-barrits-abc123"/);
    assert.match(source, /export default manifest/);
  });

  it("handles empty banner", () => {
    const source = createManifestModuleSource(makeManifest(), "");
    assert.ok(source.startsWith("\n"));
  });
});

describe("createPluginBaseOptions", () => {
  it("uses defaultVirtualModuleId when virtualModuleId not provided", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
    });
    assert.equal(opts.virtualModuleId, "barrits:manifest");
    assert.equal(opts.resolvedVirtualModuleId, "\0:barrits:manifest");
    assert.equal(opts.manifestPath, undefined);
    assert.equal(opts.packageOptions, undefined);
  });

  it("accepts explicit virtualModuleId", () => {
    const opts = createPluginBaseOptions({
      virtualModuleId: "custom:manifest",
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
    });
    assert.equal(opts.virtualModuleId, "custom:manifest");
    assert.equal(opts.resolvedVirtualModuleId, "\0:custom:manifest");
  });

  it("resolves manifestPath from direct option", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
      manifestPath: "/direct/manifest.json",
    });
    assert.equal(opts.manifestPath, "/direct/manifest.json");
  });

  it("resolves manifestPath from package options", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
      package: { manifestPath: "/package/manifest.json" },
    });
    assert.equal(opts.manifestPath, "/package/manifest.json");
  });

  it("package options includes resolved manifestPath", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
      manifestPath: "/direct/manifest.json",
      package: { projectRoot: "/project" },
    });
    assert.equal(opts.manifestPath, "/direct/manifest.json");
    assert.ok(opts.packageOptions);
    assert.equal(opts.packageOptions!.manifestPath, "/direct/manifest.json");
  });

  it("creates packageOptions when only manifestPath provided", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "\0",
      manifestPath: "/only-manifest.json",
    });
    assert.ok(opts.packageOptions);
    assert.equal(opts.packageOptions!.manifestPath, "/only-manifest.json");
  });

  it("uses different resolvedPrefix", () => {
    const opts = createPluginBaseOptions({
      defaultVirtualModuleId: "barrits:manifest",
      resolvedPrefix: "virtual",
    });
    assert.equal(opts.resolvedVirtualModuleId, "virtual:barrits:manifest");
  });
});

describe("loadManifest", () => {
  it("reads and parses a valid manifest file", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const manifestPath = join(dir, "manifest.json");
    const manifest = makeManifest({ projectRoot: dir });
    await writeFile(manifestPath, JSON.stringify(manifest), "utf8");

    const loaded = await loadManifest(manifestPath);
    assert.equal(loaded.checksum, manifest.checksum);
    assert.equal(loaded.projectRoot, dir);
  });

  it("throws on invalid JSON", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const manifestPath = join(dir, "bad.json");
    await writeFile(manifestPath, "not json", "utf8");

    await assert.rejects(async () => loadManifest(manifestPath));
  });

  it("throws on missing file", async () => {
    await assert.rejects(async () => loadManifest("/nonexistent/manifest.json"));
  });
});

describe("resolvePackageAutomationOptions", () => {
  it("returns defaults when no options and no config file", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const opts = await resolvePackageAutomationOptions({}, dir);
    assert.equal(opts.projectRoot, dir);
    assert.equal(opts.manifestPath, undefined);
    assert.equal(opts.autoManifest, true);
    assert.equal(opts.automationDirectory, ".barrits");
  });

  it("applies explicit options over defaults", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const opts = await resolvePackageAutomationOptions(
      {
        projectRoot: dir,
        manifestPath: "/custom/manifest.json",
        autoManifest: false,
        automationDirectory: ".cache/barrits",
      },
      dir,
    );
    assert.equal(opts.projectRoot, dir);
    assert.equal(opts.manifestPath, "/custom/manifest.json");
    assert.equal(opts.autoManifest, false);
    assert.equal(opts.automationDirectory, ".cache/barrits");
  });

  it("uses fallbackProjectRoot when projectRoot not provided", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const opts = await resolvePackageAutomationOptions({}, dir);
    assert.equal(opts.projectRoot, dir);
  });
});

describe("loadManifestOrCreate", () => {
  it("loads manifest when manifestPath is provided", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const manifestPath = join(dir, "manifest.json");
    const manifest = makeManifest({ projectRoot: dir });
    await writeFile(manifestPath, JSON.stringify(manifest), "utf8");

    const result = await loadManifestOrCreate(manifestPath);
    assert.ok(result);
    assert.equal(result!.checksum, manifest.checksum);
  });

  it("returns null when no manifestPath and no barrits directory", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const result = await loadManifestOrCreate(undefined, dir);
    assert.equal(result, null);
  });
});

describe("loadManifestForPackage", () => {
  it("loads manifest when options contain manifestPath", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const manifestPath = join(dir, "manifest.json");
    const manifest = makeManifest({ projectRoot: dir });
    await writeFile(manifestPath, JSON.stringify(manifest), "utf8");

    const result = await loadManifestForPackage({
      projectRoot: dir,
      manifestPath,
    });
    assert.ok(result);
    assert.equal(result!.checksum, manifest.checksum);
  });

  it("returns null when no manifest path and autoManifest is false", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const result = await loadManifestForPackage({
      projectRoot: dir,
      autoManifest: false,
    });
    assert.equal(result, null);
  });

  it("returns null when no manifest path and no barrits directory", async () => {
    const dir = await mkdtemp(join(tmpdir(), "barrits-plugins-")); tempDirs.add(dir);
    const result = await loadManifestForPackage({
      projectRoot: dir,
      autoManifest: true,
    });
    assert.equal(result, null);
  });
});
