import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { defineBarritsPackage, toBarritsAutomationOptions } from "../src/barrits/package";
import { barritsRollupPlugin } from "../src/barrits/plugins/rollup";
import { extractManifestFromModuleSource, normalizePathSlashes, writeProjectFile } from "./helpers/fixtures";

test("rollup plugin accepts package-first automation options", async () => {
  const projectRoot = await mkdtemp(join(tmpdir(), "barrits-rollup-plugin-"));

  await writeProjectFile(projectRoot, "barrits/logic/index.ts", 'export { duplicar } from "./duplicar";\n');
  await writeProjectFile(projectRoot, "barrits/logic/duplicar.ts", "export const duplicar = (value: number) => value * 2;\n");

  const plugin = barritsRollupPlugin({
    package: toBarritsAutomationOptions(defineBarritsPackage({ runtime: "node", projectRoot })),
  });

  const resolvedId = await plugin.resolveId?.("barrits:manifest");
  assert.equal(resolvedId, "\0:barrits:manifest");

  const source = await plugin.load?.(resolvedId ?? "");
  assert.equal(typeof source, "string");
  assert.match(source ?? "", /Generated by barrits Rollup plugin/);

  const manifest = extractManifestFromModuleSource(source ?? "");
  assert.ok(manifest);
  assert.deepEqual(manifest?.domains, ["logic"]);
  assert.deepEqual(manifest?.traitDescriptors, []);
  assert.deepEqual(manifest?.traitDiagnostics, []);
  assert.equal(manifest?.projectRoot, normalizePathSlashes(projectRoot));
});
