import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { generateOpenApiSchema } from "../src/barrits/schema/openapi";
import type { BarritsBuildManifest } from "../src/barrits/sdk/contracts";

const makeManifest = (descriptors: Array<{ name: string; tags?: readonly string[]; summary?: string }>): BarritsBuildManifest => ({
  projectRoot: "/test",
  generatedAt: "2026-07-02T00:00:00.000Z",
  checksum: "sha256-barrits-test",
  strategy: "current-directory",
  barritsDirectory: "/test/barrits",
  discoveryRoots: [],
  filesCount: 0,
  exportsCount: 0,
  publicExportsCount: 0,
  internalExportsCount: 0,
  barrelsCount: 0,
  traitDescriptors: descriptors.map((d) => ({
    name: d.name,
    bindingName: d.name,
    bindingKind: "const" as const,
    sourceFile: `traits/${d.name}.ts`,
    provides: [],
    requires: [],
    conflicts: [],
    state: [],
    consumes: [],
    tags: d.tags ?? [],
    runtimes: [],
    summary: d.summary,
  })),
  traitDiagnostics: [],
  importActions: [],
  collisions: [],
  domains: [],
});

describe("generateOpenApiSchema", () => {
  it("returns valid OpenAPI 3.1 structure", () => {
    const schema = generateOpenApiSchema(makeManifest([]));
    assert.equal(schema.openapi, "3.1.0");
    assert.ok(schema.info);
    assert.ok(schema.paths);
    assert.ok(schema.components);
  });

  it("uses default title, version, and description", () => {
    const schema = generateOpenApiSchema(makeManifest([]));
    assert.equal(schema.info.title, "Barrits Managed API");
    assert.equal(schema.info.version, "1.0.0");
    assert.equal(schema.info.description, "Automatically generated by Barrits AST Discovery.");
  });

  it("accepts custom options", () => {
    const schema = generateOpenApiSchema(makeManifest([]), {
      title: "My API",
      version: "2.0.0",
      description: "Custom description",
    });
    assert.equal(schema.info.title, "My API");
    assert.equal(schema.info.version, "2.0.0");
    assert.equal(schema.info.description, "Custom description");
  });

  it("returns empty paths when no http-endpoint tags", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "myTrait", tags: ["storage"] },
    ]));
    assert.equal(Object.keys(schema.paths).length, 0);
  });

  it("generates a path for http-endpoint tagged descriptor", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "createUserEndpoint", tags: ["http-endpoint"] },
    ]));
    assert.ok(schema.paths["/createuser"]);
    assert.equal(schema.paths["/createuser"].post.operationId, "createUserEndpoint");
    assert.equal(schema.paths["/createuser"].post.summary, "Executes createUserEndpoint");
  });

  it("uses summary from descriptor when available", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "loginEndpoint", tags: ["http-endpoint"], summary: "Authenticates a user" },
    ]));
    assert.equal(schema.paths["/login"].post.summary, "Authenticates a user");
  });

  it("detects endpoint by name even without http-endpoint tag", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "loginEndpoint" },
    ]));
    assert.ok(schema.paths["/login"]);
  });

  it("generates multiple paths for multiple endpoints", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "createUserEndpoint", tags: ["http-endpoint"] },
      { name: "deleteUserEndpoint", tags: ["http-endpoint"] },
    ]));
    assert.equal(Object.keys(schema.paths).length, 2);
    assert.ok(schema.paths["/createuser"]);
    assert.ok(schema.paths["/deleteuser"]);
  });

  it("generates POST handler with 200 response", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "testEndpoint", tags: ["http-endpoint"] },
    ]));
    const handler = schema.paths["/test"].post;
    assert.ok(handler.responses["200"]);
    assert.equal(handler.responses["200"].description, "Successful response");
  });

  it("handles descriptor names without 'endpoint' suffix", () => {
    const schema = generateOpenApiSchema(makeManifest([
      { name: "health", tags: ["http-endpoint"] },
    ]));
    assert.ok(schema.paths["/health"]);
  });

  it("throws on null manifest", () => {
    assert.throws(() => (generateOpenApiSchema as any)(null), TypeError);
  });

  it("throws on undefined manifest", () => {
    assert.throws(() => (generateOpenApiSchema as any)(undefined), TypeError);
  });
});
