import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { defineBarritsPackage, toBarritsAutomationOptions } from "../src/barrits/package";
import { barritsVitePlugin } from "../src/barrits/plugins/vite";
import { extractManifestFromModuleSource, normalizePathSlashes, writeProjectFile } from "./helpers/fixtures";
import { runCommand } from "./helpers/process";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const publishedRootEntryPath = pathToFileURL(join(repositoryRoot, "dist", "src", "index.js")).href;
const publishedViteEntryPath = pathToFileURL(join(repositoryRoot, "dist", "src", "barrits", "plugins", "vite.js")).href;

test("vite plugin accepts package-first automation options", async () => {
  const projectRoot = await mkdtemp(join(tmpdir(), "barrits-vite-plugin-"));

  await writeProjectFile(projectRoot, "barrits/logic/index.ts", 'export { duplicar } from "./duplicar";\n');
  await writeProjectFile(projectRoot, "barrits/logic/duplicar.ts", "export const duplicar = (value: number) => value * 2;\n");

  const barritsPackage = defineBarritsPackage({
    runtime: "react",
    projectRoot,
  });
  const plugin = barritsVitePlugin({ package: toBarritsAutomationOptions(barritsPackage) });
  const resolvedId = await plugin.resolveId?.("virtual:barrits/manifest");

  assert.ok(resolvedId);

  const source = await plugin.load?.(resolvedId);
  assert.equal(typeof source, "string");
  assert.match(source ?? "", /Generated by barrits Vite plugin/);

  const manifest = extractManifestFromModuleSource(source ?? "");
  assert.ok(manifest);
  assert.deepEqual(manifest?.domains, ["logic"]);
  assert.deepEqual(manifest?.traitDescriptors, []);
  assert.deepEqual(manifest?.traitDiagnostics, []);
  assert.equal(manifest?.projectRoot, normalizePathSlashes(projectRoot));
});

test("published vite surface imports cleanly in an ESM process", async () => {
  const script = [
    `import { defineBarritsPackage, toBarritsAutomationOptions } from ${JSON.stringify(publishedRootEntryPath)};`,
    `import { barritsVitePlugin } from ${JSON.stringify(publishedViteEntryPath)};`,
    "",
    'const options = toBarritsAutomationOptions(defineBarritsPackage({ runtime: "browser", watch: "auto" }));',
    "const plugin = barritsVitePlugin({ package: options });",
    'console.log(JSON.stringify({ name: plugin.name }));',
  ].join("\n");

  const result = await runCommand(process.execPath, ["--input-type=module", "--eval", script], repositoryRoot, process.env);

  assert.equal(result.exitCode, 0, result.stderr);
  assert.match(result.stdout, /barrits-vite-plugin/);
  assert.equal(result.stderr.trim(), "");
});
