import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { defineBarritsPackage, toBarritsAutomationOptions } from "../src/barrits/package";
import { BarritsWebpackPlugin } from "../src/barrits/plugins/webpack";

test("webpack plugin materializes a manifest module and aliases it", async () => {
  const tempDirectory = await mkdtemp(join(tmpdir(), "barrits-webpack-plugin-"));
  const manifestPath = join(tempDirectory, "build-manifest.json");
  await writeFile(manifestPath, JSON.stringify({
    generatedAt: "2026-04-06T00:00:00.000Z",
    projectRoot: ".",
    barritsDirectory: "./barrits",
    strategy: "direct-child",
    filesCount: 1,
    exportsCount: 1,
    publicExportsCount: 1,
    internalExportsCount: 0,
    barrelsCount: 1,
    domains: ["logic"],
    traitDescriptors: [],
    traitDiagnostics: [],
    importActions: [],
  }), "utf8");

  let beforeRunCallback: (() => Promise<void>) | undefined;
  const compiler = {
    context: tempDirectory,
    options: {} as { resolve?: { alias?: Record<string, string> } },
    hooks: {
      beforeRun: {
        tapPromise: (_name: string, callback: () => Promise<void>) => {
          beforeRunCallback = callback;
        },
      },
      watchRun: {
        tapPromise: () => undefined,
      },
    },
  };

  const plugin = new BarritsWebpackPlugin({ manifestPath });
  plugin.apply(compiler);

  assert.equal(compiler.options.resolve?.alias?.["barrits-manifest"] !== undefined, true);
  assert.ok(beforeRunCallback);

  await beforeRunCallback?.();

  const generatedModulePath = compiler.options.resolve?.alias?.["barrits-manifest"];
  assert.ok(generatedModulePath);

  const generatedModuleSource = await readFile(generatedModulePath, "utf8");
  assert.match(generatedModuleSource, /Generated by barrits Webpack plugin/);
  assert.match(generatedModuleSource, /"domains":\s*\[\s*"logic"/m);
  assert.match(generatedModuleSource, /"traitDescriptors":\s*\[\s*\]/m);
  assert.match(generatedModuleSource, /"traitDiagnostics":\s*\[\s*\]/m);
});

test("webpack plugin also accepts package-first automation options", async () => {
  const tempDirectory = await mkdtemp(join(tmpdir(), "barrits-webpack-package-"));
  const manifestPath = join(tempDirectory, "build-manifest.json");
  await writeFile(manifestPath, JSON.stringify({
    generatedAt: "2026-04-06T00:00:00.000Z",
    projectRoot: tempDirectory,
    barritsDirectory: join(tempDirectory, "barrits"),
    strategy: "direct-child",
    filesCount: 1,
    exportsCount: 1,
    publicExportsCount: 1,
    internalExportsCount: 0,
    barrelsCount: 1,
    domains: ["logic"],
    traitDescriptors: [],
    traitDiagnostics: [],
    importActions: [],
  }), "utf8");

  let beforeRunCallback: (() => Promise<void>) | undefined;
  const compiler = {
    context: tempDirectory,
    options: {} as { resolve?: { alias?: Record<string, string> } },
    hooks: {
      beforeRun: {
        tapPromise: (_name: string, callback: () => Promise<void>) => {
          beforeRunCallback = callback;
        },
      },
      watchRun: {
        tapPromise: () => undefined,
      },
    },
  };

  const barritsPackage = defineBarritsPackage({
    runtime: "node",
    projectRoot: tempDirectory,
    manifestPath,
  });
  const plugin = new BarritsWebpackPlugin({ package: toBarritsAutomationOptions(barritsPackage) });
  plugin.apply(compiler);

  assert.ok(beforeRunCallback);
  await beforeRunCallback?.();

  const generatedModulePath = compiler.options.resolve?.alias?.["barrits-manifest"];
  assert.ok(generatedModulePath);

  const generatedModuleSource = await readFile(generatedModulePath, "utf8");
  assert.match(generatedModuleSource, /"projectRoot":\s*"/);
  assert.match(generatedModuleSource, /"domains":\s*\[\s*"logic"/m);
  assert.match(generatedModuleSource, /"traitDescriptors":\s*\[\s*\]/m);
  assert.match(generatedModuleSource, /"traitDiagnostics":\s*\[\s*\]/m);
});