import type { BarritsImportAction, BarritsImportFilters, BarritsImportWriteMode, BarritsIntegrationGraph } from "./contracts";

export const AUTO_IMPORTS_START = "// barrits:auto-imports:start";
export const AUTO_IMPORTS_END = "// barrits:auto-imports:end";

const toObjectKey = (value: string): string => {
  return JSON.stringify(value);
};

const sortActions = (actions: readonly BarritsImportAction[]): BarritsImportAction[] => {
  return [...actions].sort((left, right) => {
    if (left.domain === right.domain) {
      if (left.exportName === right.exportName) {
        return left.kind.localeCompare(right.kind);
      }

      return left.exportName.localeCompare(right.exportName);
    }

    return left.domain.localeCompare(right.domain);
  });
};

export const createImportsModuleSource = (graph: BarritsIntegrationGraph): string => {
  const actions = sortActions(graph.importActions);
  const lines: string[] = [
    "// Generated by barrits. Do not edit manually.",
    "",
    `export const generatedAt = ${JSON.stringify(new Date().toISOString())};`,
    `export const barritsDirectory = ${JSON.stringify(graph.barritsDirectory)};`,
    `export const projectRoot = ${JSON.stringify(graph.projectRoot)};`,
    "",
    "export const importActions = [",
  ];

  for (const action of actions) {
    lines.push(
      "  {",
      `    exportName: ${JSON.stringify(action.exportName)},`,
      `    domain: ${JSON.stringify(action.domain)},`,
      `    sourceFile: ${JSON.stringify(action.sourceFile)},`,
      `    kind: ${JSON.stringify(action.kind)},`,
      `    statement: ${JSON.stringify(action.statement)},`,
      "  },",
    );
  }

  lines.push(
    "] as const;",
    "",
    "export const importMap = {",
  );

  const actionGroups = new Map<string, BarritsImportAction[]>();

  for (const action of actions) {
    const existingActions = actionGroups.get(action.exportName);

    if (existingActions) {
      existingActions.push(action);
      continue;
    }

    actionGroups.set(action.exportName, [action]);
  }

  for (const [exportName, groupedActions] of actionGroups.entries()) {
    lines.push(`  ${toObjectKey(exportName)}: {`);

    for (const action of groupedActions) {
      lines.push(`    ${toObjectKey(action.kind)}: ${JSON.stringify(action.statement)},`);
    }

    lines.push("  },");
  }

  lines.push(
    "} as const;",
    "",
    "export const namedImports = importActions.filter((action) => action.kind === \"named-import\");",
    "export const namespaceAccess = importActions.filter((action) => action.kind === \"namespace-access\");",
    "export const aliasNamespaceAccess = importActions.filter((action) => action.kind === \"alias-namespace-access\");",
    "",
  );

  return lines.join("\n");
};

const dedupeActions = (
  actions: readonly BarritsImportAction[],
  mode: BarritsImportWriteMode,
): BarritsImportAction[] => {
  const seen = new Set<string>();
  const filtered: BarritsImportAction[] = [];

  for (const action of sortActions(actions)) {
    if (action.kind !== mode) {
      continue;
    }

    if (seen.has(action.statement)) {
      continue;
    }

    seen.add(action.statement);
    filtered.push(action);
  }

  return filtered;
};

export const filterImportActions = (
  graph: BarritsIntegrationGraph,
  filters: BarritsImportFilters = {},
): BarritsIntegrationGraph => {
  const domainFilter = filters.domains ? new Set(filters.domains) : null;
  const exportFilter = filters.exports ? new Set(filters.exports) : null;
  const kindFilter = filters.kinds ? new Set(filters.kinds) : null;

  const importActions = graph.importActions.filter((action) => {
    if (domainFilter && !domainFilter.has(action.domain)) {
      return false;
    }

    if (exportFilter && !exportFilter.has(action.exportName)) {
      return false;
    }

    if (kindFilter && !kindFilter.has(action.kind)) {
      return false;
    }

    return true;
  });

  return {
    ...graph,
    importActions,
  };
};

export const createImportBlock = (
  graph: BarritsIntegrationGraph,
  mode: BarritsImportWriteMode = "named-import",
): string => {
  if (mode === "named-import") {
    const names = dedupeActions(graph.importActions, "named-import")
      .map((action) => action.exportName)
      .filter((value, index, values) => values.indexOf(value) === index)
      .sort((left, right) => left.localeCompare(right));

    if (names.length === 0) {
      return `${AUTO_IMPORTS_START}\n${AUTO_IMPORTS_END}`;
    }

    return [AUTO_IMPORTS_START, `import { ${names.join(", ")} } from "barrits";`, AUTO_IMPORTS_END].join("\n");
  }

  const binding = mode === "namespace-access" ? "barrits" : "brt";
  return [AUTO_IMPORTS_START, `import { ${binding} } from "barrits";`, AUTO_IMPORTS_END].join("\n");
};

export const applyManagedImports = (
  source: string,
  graph: BarritsIntegrationGraph,
  mode: BarritsImportWriteMode = "named-import",
): string => {
  const importBlock = createImportBlock(graph, mode);
  const managedBlockPattern = new RegExp(`${AUTO_IMPORTS_START}[\\s\\S]*?${AUTO_IMPORTS_END}\\n?`, "m");

  if (managedBlockPattern.test(source)) {
    return source.replace(managedBlockPattern, `${importBlock}\n`);
  }

  const importMatch = source.match(/^(?:import\s.+;\r?\n)+/);

  if (importMatch) {
    return `${importMatch[0]}${importBlock}\n${source.slice(importMatch[0].length)}`;
  }

  return `${importBlock}\n${source}`;
};