import type { BarritsBuildManifest } from "../sdk/contracts";

/**
 * [EN] Options for OpenAPI schema generation.
 * [ES] Opciones para la generación del esquema OpenAPI.
 */
export type BarritsOpenApiOptions = {
  /** [EN] API Title. [ES] Título de la API. */
  title?: string;
  /** [EN] API Version. [ES] Versión de la API. */
  version?: string;
  /** [EN] API Description. [ES] Descripción de la API. */
  description?: string;
};

/**
 * [EN] Generates an OpenAPI v3.1 schema from a BarritsBuildManifest.
 * [ES] Genera un esquema OpenAPI v3.1 desde un BarritsBuildManifest.
 *
 * @param manifest [EN] The discovery manifest. [ES] El manifiesto de descubrimiento.
 * @param options [EN] Generation options. [ES] Opciones de generación.
 */
export const generateOpenApiSchema = (manifest: BarritsBuildManifest, options: BarritsOpenApiOptions = {}): Record<string, any> => {
  const openapi = {
    openapi: "3.1.0",
    info: {
      title: options.title ?? "Barrits Managed API",
      version: options.version ?? "1.0.0",
      description: options.description ?? "Automatically generated by Barrits AST Discovery.",
    },
    paths: {} as Record<string, any>,
    components: {
      schemas: {} as Record<string, any>,
    },
  };

  for (const descriptor of manifest.traitDescriptors) {
    if (descriptor.tags.includes("http-endpoint") || descriptor.name.toLowerCase().includes("endpoint")) {
      const path = `/${descriptor.name.toLowerCase().replace(/endpoint$/, "")}`;

      openapi.paths[path] = {
        post: {
          summary: descriptor.summary ?? `Executes ${descriptor.name}`,
          operationId: descriptor.name,
          responses: {
            "200": {
              description: "Successful response",
            },
          },
        },
      };
    }
  }

  return openapi;
};
