import type { BarritsBuildManifest, BarritsTraitDescriptorInspection } from "../sdk/contracts";

/**
 * [EN] OpenAPI v3.1 document with Barrits trait-driven schema generation support.
 * [ES] Documento OpenAPI v3.1 con soporte para generación de esquemas impulsada por traits de Barrits.
 *
 * @experimental This API is experimental and subject to change.
 */
export type BarritsOpenApiDocument = {
  readonly openapi: "3.1.0";
  readonly info: {
    readonly title: string;
    readonly version: string;
    readonly description?: string;
    readonly "x-experimental"?: boolean;
  };
  readonly paths: Record<string, Record<string, unknown>>;
  readonly components: {
    readonly schemas: Record<string, unknown>;
  };
};

/**
 * [EN] Options for OpenAPI schema generation.
 * [ES] Opciones para la generación del esquema OpenAPI.
 */
export type BarritsOpenApiOptions = {
  /** [EN] API Title. [ES] Título de la API. */
  title?: string;
  /** [EN] API Version. [ES] Versión de la API. */
  version?: string;
  /** [EN] API Description. [ES] Descripción de la API. */
  description?: string;
  /** [EN] Mark as experimental. [ES] Marcar como experimental. */
  experimental?: boolean;
};

const parseTag = (tag: string): { key: string; value: string } | null => {
  const match = /^([^=]+)=([^=]+)$/.exec(tag);
  return match ? { key: match[1], value: match[2] } : null;
};

const getTraitTag = (descriptor: BarritsTraitDescriptorInspection, tagKey: string): string | undefined => {
  for (const tag of descriptor.tags) {
    const parsed = parseTag(tag);
    if (parsed?.key === tagKey) {
      return parsed.value;
    }
  }
  return undefined;
};

/**
 * [EN] Generates an OpenAPI v3.1 schema from a BarritsBuildManifest, reading trait tags for
 * endpoints (`http:method=GET|POST|...` and `http:path=/api/...`).
 * [ES] Genera un esquema OpenAPI v3.1 desde un BarritsBuildManifest, leyendo tags de traits
 * para puntos de entrada (`http:method=GET|POST|...` y `http:path=/api/...`).
 *
 * @param manifest [EN] The discovery manifest. [ES] El manifiesto de descubrimiento.
 * @param options [EN] Generation options. [ES] Opciones de generación.
 *
 * @experimental This API is experimental and subject to change.
 */
export const generateOpenApiSchema = (manifest: BarritsBuildManifest, options: BarritsOpenApiOptions = {}): BarritsOpenApiDocument => {
  const openapi: BarritsOpenApiDocument = {
    openapi: "3.1.0",
    info: {
      title: options.title ?? "Barrits Managed API",
      version: options.version ?? "1.0.0",
      description: options.description ?? "Automatically generated by Barrits AST Discovery.",
      "x-experimental": options.experimental ?? true,
    },
    paths: {},
    components: {
      schemas: {},
    },
  };

  for (const descriptor of manifest.traitDescriptors) {
    const httpMethod = getTraitTag(descriptor, "http:method");
    const httpPath = getTraitTag(descriptor, "http:path");

    if (httpMethod && httpPath) {
      const pathKey = httpPath;
      if (!openapi.paths[pathKey]) {
        openapi.paths[pathKey] = {};
      }

      const methodLower = httpMethod.toLowerCase();
      openapi.paths[pathKey][methodLower] = {
        summary: descriptor.summary ?? `Executes ${descriptor.name}`,
        operationId: descriptor.name,
        tags:
          descriptor.tags.filter((tag) => !tag.includes("=")).length > 0 ? descriptor.tags.filter((tag) => !tag.includes("=")) : undefined,
        responses: {
          "200": {
            description: "Successful response",
          },
        },
      };
      continue;
    }

    if (descriptor.tags.includes("http-endpoint") || descriptor.name.toLowerCase().includes("endpoint")) {
      const path = `/${descriptor.name.toLowerCase().replace(/endpoint$/, "")}`;
      openapi.paths[path] = {
        post: {
          summary: descriptor.summary ?? `Executes ${descriptor.name}`,
          operationId: descriptor.name,
          responses: {
            "200": {
              description: "Successful response",
            },
          },
        },
      };
    }
  }

  return openapi;
};
