/**
 * @module
 * Typed manifest and snapshot consumption helpers for runtime tooling.
 */

/** Build manifest payload generated by Barrits automation. */
export type {
  BarritsBuildManifest,
} from "./sdk/contracts";

/** Compact summary model consumed by tooling clients. */
export type {
  BarritsConsumedStateSummary,
} from "./sdk/contracts";

/** Domain-level projection used by language tools. */
export type {
  BarritsLanguageToolDomain,
} from "./sdk/contracts";

/** Snapshot projection consumed by IDE and assistant tooling. */
export type {
  BarritsLanguageToolSnapshot,
} from "./sdk/contracts";

/** Graph selection filters for focused manifest/snapshot views. */
export type {
  BarritsSelectionFilters,
} from "./sdk/contracts";

/** Watch snapshot payload generated during live automation sessions. */
export type {
  BarritsWatchSnapshot,
} from "./sdk/contracts";

/** Parses a serialized build manifest into a typed payload. */
export {
  parseBuildManifest,
} from "./sdk/consume";

/** Parses a serialized watch snapshot into a typed payload. */
export {
  parseWatchSnapshot,
} from "./sdk/consume";

/** Reads a build manifest from disk with schema validation. */
export {
  readBuildManifest,
} from "./sdk/consume";

/** Reads and summarizes a build manifest for fast tooling consumption. */
export {
  readBuildManifestSummary,
} from "./sdk/consume";

/** Reads a watch snapshot from disk with schema validation. */
export {
  readWatchSnapshot,
} from "./sdk/consume";

/** Reads and summarizes a watch snapshot for runtime dashboards. */
export {
  readWatchSnapshotSummary,
} from "./sdk/consume";

/** Reads language-tool snapshot payload used by editor integrations. */
export {
  readLanguageToolSnapshot,
} from "./sdk/consume";

/** Creates a compact summary view from a build manifest payload. */
export {
  createBuildManifestSummary,
} from "./sdk/consume";

/** Creates a compact summary view from a watch snapshot payload. */
export {
  createWatchSnapshotSummary,
} from "./sdk/consume";

/** Creates an editor-focused snapshot model for tooling pipelines. */
export {
  createLanguageToolSnapshot,
} from "./sdk/consume";